# Generated by Django 4.1.5 on 2023-01-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='artice',
            new_name='article',
        ),
    ]
